Starfield
ModOrganizer2/modorganizer-game_gamebryo pull request #43
Opened 2023-09-06 00:11 UTC by Silarn

* Add stubs / defaults for overridePluginsAreSupported and secondaryDataDIrectories
* Add zlib decompression support to save parsing

2023-09-06 06:56 UTC, Al12rs reviewed
I don't like the secondary data solution as it seems like a hack specific for starfield and not really usable for any other game.
Perhaps there is a solution that is more flexible and gives more control to game plugins.

Other than that it looked good to me. Didn't look too deep into the saves code.

2023-09-06 06:56 UTC, Al12rs commented on src/gamebryo/gamegamebryo.cpp
> +QMap<QString, QDir> GameGamebryo::secondaryDataDirectories() const
I'm not too happy with this solution. I'll probably expand on this in uibase pr.

2023-09-06 08:23 UTC, Holt59 commented
I trust you on the changes but code should be formatted.

2023-09-06 08:24 UTC, Holt59 requested changes
I trust you on the changes but code should be formatted.

2023-09-06 09:30 UTC, Silarn commented
I've reformatted the code but I think I need to make one small change to the zlib inflate code. I don't think I need to bake the start location read / seek into that function. I thought I might need the final unpack size but I don't think that's actually necessary. The other thing is I'm still not convinced it's unpacked the entire save. Though we have the date we need ultimately.

2023-09-06 09:35 UTC, Silarn commented
My current guess is that I can add up the total processed bytes for the input stream to locate where the next zlib chunk begins. The test extractions I made were always suspiciously 256k long so I have a feeling they broke up the data into 256k chunks.

2023-09-07 07:46 UTC, Al12rs approved these changes

2023-09-17 21:18 UTC, merged